version: "3"

services:
  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - $DB_PORT:3306
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - mysql-network
  app:
    build: .
    command: npm start
    ports:
      - "50051:50051"
    volumes:
      - .:/usr/app
    networks:
      - mysql-network
    depends_on:
      - database
networks:
  mysql-network:
    driver: bridge
